# Generated by Django 4.2.7 on 2024-01-16 17:58

from django.db import migrations, models
import repository.Utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='título')),
                ('description', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='Documents/', validators=[repository.Utils.validate_file_extension])),
                ('image', models.ImageField(upload_to='Documents/')),
            ],
            options={
                'verbose_name': 'documento',
            },
        ),
    ]
