# Generated by Django 4.2.7 on 2023-12-24 22:04

from django.db import migrations, models
import repository.Utils


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Documents/', validators=[repository.Utils.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
