# Generated by Django 4.2.7 on 2024-01-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='key_words',
            new_name='theme',
        ),
    ]
